[package]
name = "yt-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
rustube = "0.6.0"
serde = "1.0.218"
serde_json = "1.0.139"
youtube_dl = "0.10.0"
